### PR TITLE
Add an output formatter that prints only InstallationPath.

### PR DESCRIPTION
**Pull request by res2k**
Adds an output formatter that only prints the first encountered InstallationPath.

Why? Because that is possibly the single most interesting information 3rd party users (e.g. build systems) are interested in. In conjunction with the other command line arguments you can get the e.g. "C++ compiler location"; from there build tools are typically able to figure the rest out by themselves.
Compared to the "text" formatter this specialized "path only" formatter relieves those build tools from having to parse the output.

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by heaths** [comment]
Something like this is coming soon, but will allow the property to be specified. InstallationPath may be the more interesting property most of the time, but certainly not the only and what I have planned still allows for specifying a different format.

**Comment by res2k** [comment]
Alright, nice.
Though I want to point out that a "naked" output is valuable since it eliminates the burden of having to somehow still process the output to actually get some value. Maybe you can consider that as well.

**Comment by heaths** [comment]
That was always the intent, yes. :)

If you look at tools\Microsoft.VisualStudio.Setup.Configuration.Console.exe in the Microsoft.VisualStudio.Setup.Configuration.Native NuGet package, I have an old prototype in there (honestly, I forgot I put it in there for testing originally and some people took a dependency on it) that does exactly that. This is a more production-ready version and I'm adding back functionality as I can.

**Comment by heaths** [comment]
BTW, this functionality is in now:

```powershell
[Console]::OutputEncoding = [Text.Encoding]::Unicode
$path = vswhere.exe -property installationPath -latest
```

**Pull request closed without merging**
