### PR TITLE
Support the BuiltTools SKU

### PR DESCRIPTION
**Pull request by refack**

### CODE REVIEW

**Comment by heaths** [comment]
Should also mention that the defaults are VS because that is the main use case for *vs*where.

**Comment by refack** [comment]
IMHO you should add 'BuildTools' as a use case since that would make `vswhere` a welcome companion to the "CLI" compatible tool-set.

**Comment by heaths** [comment]
It is. Pass it to the -products command line switch. New version with -help support and more just went up.

The installer installs lots of products and more will be added. The default use case is VS (*very* different composition than built tools) but it was always my goal to support *all* products, hence the switch.

**Comment by ericoporto** [comment]
I still think vswhere not finding the build tools is the wrong approach.

**Comment by heaths** [comment]
It wasn't necessary when originally spec'd, and Build Tools back then was missing *a lot* of tools (compilers, etc.) that VS had. Changing what it detects after it had been out for a long time would be a breaking change to many build systems, hence having to opt into detecting it which you can easily do with the `-products` parameter.

To reiterate before I close this thread: we cannot responsibility change the detection to include Build Tools by default or it will be a breaking behavioral change.

**Pull request closed without merging**
